openapi: 3.0.0
info:
  title: SELVA
  version: 1.0.0
  description: Soluciones ElectrÃ³nicas Locales de Valor
servers:
  - url: https://dev.selva.fi.cr
  - url: https://selva.fi.cr
paths:
  /api/user:
    get:
      summary: Get User
      responses:
        "200":
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                      email_verified_at:
                        type: string
                        format: date-time
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
              example:
                success: true
                message: User retrieved successfully
                data:
                  id: d37da6d4-c34c-44e9-bb00-7273a378a5ad
                  name: Philippe Lamy
                  email: philippe@selva.com
                  email_verified_at: null
                  created_at: 2025-12-12T13:30:05.000000Z
                  updated_at: 2025-12-12T13:31:58.000000Z
        "401":
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    nullable: true
                  errors:
                    type: object
              example:
                success: false
                message: Unauthenticated.
                data: null
                errors: {}
      tags:
        - User
      security:
        - BearerAuth: []
  /api/payments:
    post:
      summary: Send Payment
      parameters:
        - name: X-Idempotency-Key
          in: header
          required: false
          deprecated: false
          schema: {}
          example: "{{$randomUUID}}"
      responses:
        "201":
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      payment_id:
                        type: string
                        format: uuid
                      payment_type:
                        type: string
                      status:
                        type: string
                      channel_reference:
                        type: string
              example:
                success: true
                message: Payment initiated successfully
                data:
                  payment_id: 5e74bd6c-46c5-4933-b46a-bb081e71663e
                  payment_type: pin
                  status: pending
                  channel_reference: "2025123100001198137477666"
        "409":
          description: Already use X-Idempotency-Key (duplicated request)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    nullable: true
                  errors:
                    type: object
                    properties:
                      payment_id:
                        type: string
                        format: uuid
                      payment_type:
                        type: string
                      status:
                        type: string
              example:
                success: false
                message: Payment already processed
                data: null
                errors:
                  payment_id: 122434f8-0b17-4aa3-8063-d8baf978b617
                  payment_type: pin
                  status: pending
      tags:
        - Payments
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example: |-
              {
                  "from_account_id": "",
                  "amount": "",
                  "recipient_iban": ""
                  // "recipient_phone": ""
                  // "recipient_email": "",
                  // "description": "",
                  // "reference": ""
              }
  /api/payments/validate:
    post:
      summary: Validate Payment
      parameters:
        - name: X-Idempotency-Key
          in: header
          required: false
          deprecated: false
          schema: {}
          example: "{{$randomUUID}}"
      responses: {}
      tags:
        - Payments
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example: |-
              {
                  "from_account_id": "",
                  "amount": "",
                  "recipient_id": "",
                  // "recipient_iban": ""
                  "recipient_phone": ""
                  // "recipient_email": "",
                  // "description": "",
                  // "reference": ""
              }
  /api/payments/{id}:
    get:
      summary: Get Payment Details
      responses: {}
      tags:
        - Payments
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/payments/history:
    get:
      summary: Get Historical Transfers
      parameters:
        - name: payment_method
          in: query
          required: false
          deprecated: false
          schema: {}
          example: pin
        - name: transfer_type
          in: query
          required: false
          deprecated: false
          schema: {}
          example: debit
        - name: recipient_identifier
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "111090807"
        - name: limit
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "10"
        - name: offset
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "0"
      responses: {}
      tags:
        - Payments
      security:
        - BearerAuth: []
  /api/payments/service-status:
    get:
      summary: Get Service Status
      responses: {}
      tags:
        - Payments
      security:
        - BearerAuth: []
  /api/accounts/{id}:
    get:
      summary: Get Account
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/accounts:
    get:
      summary: List Accounts
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    post:
      summary: Create Account
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency:
                  type: string
            example:
              currency: ""
  /api/accounts/{id}/balance:
    get:
      summary: Get Account Balance
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/accounts/{id}/details:
    get:
      summary: Get Account Details
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/accounts/{id}/transfers:
    get:
      summary: "[DEPRECATED] List Account Transfers"
      parameters:
        - name: from
          in: query
          schema:
            type: string
          example: "{{from}}"
        - name: to
          in: query
          schema:
            type: string
          example: "{{to}}"
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/accounts/{id}/kyc:
    get:
      summary: "[DEPRECATED] Get Account KYC"
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/accounts/{id}/transfers/{transferId}:
    get:
      summary: Get Account Transfer By Id
      responses: {}
      tags:
        - Account
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: transferId
        in: path
        required: true
        schema:
          type: string
  /api/phone/information:
    get:
      summary: Verify Phone Is Registered
      parameters:
        - name: phone_number
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "{{phone_number}}"
      responses: {}
      tags:
        - Verification
      security:
        - BearerAuth: []
  /api/iban/information:
    get:
      summary: Verify IBAN Is Registered
      parameters:
        - name: iban
          in: query
          required: false
          deprecated: false
          schema: {}
          example: "{{recipient_iban}}"
      responses: {}
      tags:
        - Verification
      security:
        - BearerAuth: []
  /api/webhooks/subscriptions/{id}:
    get:
      summary: Get Webhook
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    delete:
      summary: Delete Webhook
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
  /api/webhooks/subscriptions:
    get:
      summary: List Webhooks
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: "1"
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
    post:
      summary: Create Webhook
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                events:
                  type: string
                max_attempts:
                  type: string
                headers:
                  type: object
                  properties:
                    X-Custom-Header:
                      type: string
            example:
              url: ""
              events: ""
              max_attempts: ""
              headers:
                X-Custom-Header: value
  /api/webhooks/subscriptions/{id}/suspend:
    post:
      summary: Suspend Webhook
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/webhooks/subscriptions/{id}/resume:
    post:
      summary: Resume Webhook
      responses: {}
      tags:
        - Webhook
        - server
      security:
        - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /api/kindo/pin/NotifyIncomingTransfers:
    post:
      summary: Simulate PIN-Based Credit Transfer
      parameters:
        - name: Signature
          in: header
          required: false
          deprecated: false
          schema: {}
          example: 4e0080ca1c99925242c1c2ef9885d4efa2719b7669dfb8b9ed0a096738b29917
      responses: {}
      tags:
        - Webhook
        - client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                SecurityInfo:
                  type: string
                Transfers:
                  type: array
                  items:
                    type: object
                    properties:
                      CGPRefNumber:
                        type: integer
                      SINPERefNumber:
                        type: string
                        format: utc-millisec
                      AuthorizationDate:
                        type: string
                        format: style
                      OriginEntity:
                        type: string
                      OriginCustomer:
                        type: object
                        properties:
                          Id:
                            type: string
                          IdType:
                            type: string
                            format: utc-millisec
                          Name:
                            type: string
                          IBAN:
                            type: string
                      DestinationCustomer:
                        type: object
                        properties:
                          Id:
                            type: string
                          IdType:
                            type: string
                            format: utc-millisec
                          Name:
                            type: string
                          IBAN:
                            type: string
                      Amount:
                        type: integer
                      CurrencyCode:
                        type: string
                      Description:
                        type: string
            example:
              SecurityInfo: >-
                7523e3fe7208500918ccee1c457d3c604de4e5d4f415547b821d6a6e8281cb779353352051a03baf4b4b84b95d7612506812d368e23e55fa79de2ab31e31d64e
              Transfers:
                - CGPRefNumber: 2000
                  SINPERefNumber: "2025112481483010196438101"
                  AuthorizationDate: "2025-11-24T11:29:46"
                  OriginEntity: Banco Nacional
                  OriginCustomer:
                    Id: 01-0000-0000
                    IdType: "0"
                    Name: Bobby Fisher
                    IBAN: CR92015101410010010721
                  DestinationCustomer:
                    Id: 07-0258-0327
                    IdType: "0"
                    Name: Leister Alvarado
                    IBAN: CR26037010600861494409
                  Amount: 10001
                  CurrencyCode: CRC
                  Description: Transf PIN de Prueba
  /api/kindo/sinpe-movil/NotifyIncomingTransfers:
    post:
      summary: Simulate SINPE-Based Credit Transfer
      parameters:
        - name: Signature
          in: header
          required: false
          deprecated: false
          schema: {}
          example: 4e0080ca1c99925242c1c2ef9885d4efa2719b7669dfb8b9ed0a096738b29917
      responses: {}
      tags:
        - Webhook
        - client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                SecurityInfo:
                  type: string
                Transfers:
                  type: array
                  items:
                    type: object
                    properties:
                      CGPRefNumber:
                        type: integer
                      SINPERefNumber:
                        type: string
                        format: utc-millisec
                      AuthorizationDate:
                        type: string
                        format: style
                      OriginCustomer:
                        type: object
                        properties:
                          Id:
                            type: string
                          IdType:
                            type: string
                            format: utc-millisec
                          Name:
                            type: string
                          Phone:
                            type: string
                            format: utc-millisec
                      DestinationCustomer:
                        type: object
                        properties:
                          Id:
                            type: string
                          IdType:
                            type: string
                            format: utc-millisec
                          Name:
                            type: string
                          IBAN:
                            type: string
                          Phone:
                            type: string
                            format: utc-millisec
                      Amount:
                        type: integer
                      CurrencyCode:
                        type: string
                      Description:
                        type: string
            example:
              SecurityInfo: >-
                7523e3fe7208500918ccee1c457d3c604de4e5d4f415547b821d6a6e8281cb779353352051a03baf4b4b84b95d7612506812d368e23e55fa79de2ab31e31d64e
              Transfers:
                - CGPRefNumber: 2001
                  SINPERefNumber: "2025112481483010196438103"
                  AuthorizationDate: "2025-11-24T11:29:46"
                  OriginCustomer:
                    Id: 01-0000-0000
                    IdType: "0"
                    Name: Bobby Fisher
                    Phone: "88881234"
                  DestinationCustomer:
                    Id: 07-0258-0327
                    IdType: "0"
                    Name: Leister Alvarado
                    IBAN: CR26037010600861494409
                    Phone: "88509676"
                  Amount: 2500
                  CurrencyCode: CRC
                  Description: Transf SINPE de Prueba
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
